import { BlockIdGenerator } from './block-id-generator';

/**
 * Implementation of {@link BlockIdGenerator}
 *
 *
 * The ID is generated by linear incrementation of shared counter.
 */
export class IncrementalBlockIdGenerator implements BlockIdGenerator {
  /**
   * Counter of generated IDs
   */
  private counter = 0;

  generate(): string {
    return `${this.counter++}`;
  }
}
