import { randomUUID } from 'crypto';

import { BlockIdGenerator } from './block-id-generator';

/**
 * Implementation of {@link BlockIdGenerator}
 *
 *
 * The ID is generated by calling {@link randomUUID} function from 'crypto'
 * package
 */
export class UuidBlockIdGenerator implements BlockIdGenerator {
  generate(): string {
    return randomUUID().replace(/-/g, '_');
  }
}
