export enum BlockKind {
  BINARY_EXPRESSION_DECLARATION,
  BLOCK_DECLARATION,
  BREAK_DECLARATION,
  CONTINUE_DECLARATION,
  EMPTY_DECLARATION,
  FOR_DECLARATION,
  FOR_IN_DECLARATION,
  FOR_OF_DECLARATION,
  PARENT_DECLARATION,
  IF_ELSE_DECLARATION,
  METHOD_CALL_DECLARATION,
  NAMED_BLOCK_DECLARATION,
  PARALLEL_BLOCK_DECLARATION,
  RETURN_DECLARATION,
  TEXT_DECLARATION,
  THROW_DECLARATION,
  TRY_CATCH_DECLARATION,
  VARIABLE_DECLARATION,
  VARIABLE_LIST_DECLARATION
}

export const CYCLE_BLOCK_KIND: BlockKind[] = [
  BlockKind.FOR_DECLARATION,
  BlockKind.FOR_IN_DECLARATION,
  BlockKind.FOR_OF_DECLARATION,
];
